import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Registry } from '../js/build/registry.js';
import { idFromEnglishName } from '../js/data/characters/_defineCharacter.js';

import '../js/data/characters/_index.js';

const EXPECTED_CHARACTER_ENGLISH_NAMES = Object.freeze([
    'Acheron',
    'Aglaea',
    'Anaxa',
    'Archer',
    'Argenti',
    'Arlan',
    'Ashveil',
    'Asta',
    'Aventurine',
    'Bailu',
    'Black Swan',
    'Blade',
    'Boothill',
    'Bronya',
    'Castorice',
    'Cerydra',
    'Cipher',
    'Clara',
    'Cyrene',
    'Dan Heng',
    'Dan Heng • Imbibitor Lunae',
    'Dan Heng • Permansor Terrae',
    'Dr. Ratio',
    'Evanescia',
    'Evernight',
    'Feixiao',
    'Firefly',
    'Fu Xuan',
    'Fugue',
    'Gallagher',
    'Gepard',
    'Gilgamesh',
    'Guinaifen',
    'Hanya',
    'Herta',
    'Himeko',
    'Himeko • Nova',
    'Hook',
    'Huohuo',
    'Hyacine',
    'Hysilens',
    'Jade',
    'Jiaoqiu',
    'Jing Yuan',
    'Jingliu',
    'Kafka',
    'Lingsha',
    'Luka',
    'Luocha',
    'Lynx',
    'March 7th',
    'March 7th (The Hunt)',
    'Misha',
    'Mortenax Blade',
    'Moze',
    'Mydei',
    'Natasha',
    'Pela',
    'Phainon',
    'Qingque',
    'Rappa',
    'Rin Tohsaka',
    'Robin',
    'Ruan Mei',
    'Saber',
    'Sampo',
    'Seele',
    'Serval',
    'Silver Wolf',
    'Silver Wolf LV.999',
    'Sparkle',
    'Sparxie',
    'Sunday',
    'Sushang',
    'The Dahlia',
    'The Herta',
    'Tingyun',
    'Topaz & Numby',
    'Trailblazer (Destruction)',
    'Trailblazer (Preservation)',
    'Trailblazer (Harmony)',
    'Trailblazer (Remembrance)',
    'Trailblazer (Elation)',
    'Tribbie',
    'Welt',
    'Xueyi',
    'Yanqing',
    'Yao Guang',
    'Yukong',
    'Yunli',
]);

test('ver4.4までのキャラクター英名リストがすべて登録されている', () => {
    const expectedIds = EXPECTED_CHARACTER_ENGLISH_NAMES.map(idFromEnglishName);
    assert.equal(new Set(expectedIds).size, expectedIds.length, 'expected id list has duplicates');

    for (const id of expectedIds) {
        assert.ok(Registry.character.has(id), `character id "${id}" is missing`);
    }
});
